### ISSUE TITLE
update npm packages

### ISSUE THREAD

**Issue by eduarguzher** [joselfonseca/laravel-api#1]
In order to make it work in a completely new project I had to change
 in `package.json` : 
`node_modules/cross-env/bin/cross-env.js`
 To -> `node_modules/cross-env/dist/bin/cross-env.js`
and update laravel-mix package using `"laravel-mix": "0.*",` 
just to let you know and check if it was a global issue or just mine

**Comment by joselfonseca** [comment]
Thanks! I do have to update the package.json file. Will do it as soon as i get a chance.

**Comment by joselfonseca** [comment]
fixed in https://github.com/joselfonseca/laravel-api/commit/f7ef7c32742be9df08f611d98bfcfe829a3e56cd
