### ISSUE TITLE
Help, I do not work the routes

### ISSUE THREAD

**Issue by Elema82** [joselfonseca/laravel-api#10]
Hello, download and install the repository step by step and did not work the calls oauth2 of passport. The tests I did with postman tool

regards.

**Comment by joselfonseca** [comment]
Hello,

Can you please provide reproduction steps and screenshots if possible please. 

Thanks.

**Comment by Elema82** [comment]
I install with nginx & php7.
* Download
* Installation by readme.md 
* check on console the list routes : 
vagrant@homestead:~/Sites/new-api$ php artisan route:list
+--------+----------+-----------------------------------------+------+----------------------------------------------------------------------------+------------+
| Domain | Method   | URI                                     | Name | Action                                                                     | Middleware |
+--------+----------+-----------------------------------------+------+----------------------------------------------------------------------------+------------+
|        | GET|HEAD | /                                       |      | App\Http\Controllers\ApiDocsController@index                               | web        |
|        | GET|HEAD | oauth/authorize                         |      | \Laravel\Passport\Http\Controllers\AuthorizationController@authorize       | web,auth   |
|        | POST     | oauth/authorize                         |      | \Laravel\Passport\Http\Controllers\ApproveAuthorizationController@approve  | web,auth   |
|        | DELETE   | oauth/authorize                         |      | \Laravel\Passport\Http\Controllers\DenyAuthorizationController@deny        | web,auth   |
|        | GET|HEAD | oauth/clients                           |      | \Laravel\Passport\Http\Controllers\ClientController@forUser                | web,auth   |
|        | POST     | oauth/clients                           |      | \Laravel\Passport\Http\Controllers\ClientController@store                  | web,auth   |
|        | PUT      | oauth/clients/{client_id}               |      | \Laravel\Passport\Http\Controllers\ClientController@update                 | web,auth   |
|        | DELETE   | oauth/clients/{client_id}               |      | \Laravel\Passport\Http\Controllers\ClientController@destroy                | web,auth   |
|        | GET|HEAD | oauth/personal-access-tokens            |      | \Laravel\Passport\Http\Controllers\PersonalAccessTokenController@forUser   | web,auth   |
|        | POST     | oauth/personal-access-tokens            |      | \Laravel\Passport\Http\Controllers\PersonalAccessTokenController@store     | web,auth   |
|        | DELETE   | oauth/personal-access-tokens/{token_id} |      | \Laravel\Passport\Http\Controllers\PersonalAccessTokenController@destroy   | web,auth   |
|        | GET|HEAD | oauth/scopes                            |      | \Laravel\Passport\Http\Controllers\ScopeController@all                     | web,auth   |
|        | POST     | oauth/token                             |      | \Laravel\Passport\Http\Controllers\AccessTokenController@issueToken        | throttle   |
|        | POST     | oauth/token/refresh                     |      | \Laravel\Passport\Http\Controllers\TransientTokenController@refresh        | web,auth   |
|        | GET|HEAD | oauth/tokens                            |      | \Laravel\Passport\Http\Controllers\AuthorizedAccessTokenController@forUser | web,auth   |
|        | DELETE   | oauth/tokens/{token_id}                 |      | \Laravel\Passport\Http\Controllers\AuthorizedAccessTokenController@destroy | web,auth   |


* test this on postman :
![captura de pantalla 2017-07-06 a la s 09 22 58](https://user-images.githubusercontent.com/25822930/27910736-ce05f316-622c-11e7-88c3-2bc22286386d.png)

**Comment by Elema82** [comment]
ok sorry, not implement this ( https://medium.com/hecho-en-laravel/dingo-api-con-passport-5652927dfaff )

now its work! 

thanks!
