### ISSUE TITLE
Facebook connect

### ISSUE THREAD

**Issue by marijang** [joselfonseca/laravel-api#11]
Can you add facebook connect/signup
route: user/facebook

**Comment by joselfonseca** [comment]
Not all projects require social login, many of the ones i've worked on are enterprise private APIs that don't use this kind of social integration, but we can think about something, maybe a separate package to integrate socialite into the API. I will leave it here also to receive opinions. 

Thanks.

**Comment by joselfonseca** [comment]
This is implementation specific and can be done with Socialite.
