### ISSUE TITLE
Error while running app:install command.

### ISSUE THREAD

**Issue by ivanjpolanco** [joselfonseca/laravel-api#12]
I get this error while running the app:install command.

Installing the app

 [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected ':', expecting ';' or '{'

Hard to tell where the problem is. Help?

**Comment by ivanjpolanco** [comment]
I made a new installation downloading the master... I works fine.

The other one was via composer, which seems outdated.

**Comment by joselfonseca** [comment]
Thanks @ivanjpolanco, I am going to check this as 3.0.1 is master and should not have any issues, by any chance did you see what version it downloaded?

**Comment by mostafa6765** [comment]
@joselfonseca , same problem facing when clone no problem . but composer system give error 
```php
[Symfony\Component\Debug\Exception\FatalErrorException]
syntax error, unexpected ':', expecting ';' or '{'
```
 that error is bellow 

```php
   public function setTransformer() :TransformerAbstract
    {
        return app(UserTransformer::class);
    }
```

**Comment by joselfonseca** [comment]
It requires PHP 7, are you using php 5.6?

https://github.com/joselfonseca/laravel-api/blob/master/composer.json#L16

**Comment by joselfonseca** [comment]
Have not been able to reproduce this issue in PHP 7+ if your using php 5.6 it won't work. A constraint for it has been added in composer.json 

Thanks!
