### ISSUE TITLE
Some issues for composer 

### ISSUE THREAD

**Issue by mostafa6765** [joselfonseca/laravel-api#13]
install project by composer facing some problem .and missing doc........
1.app:install not run . error bellow
```php
public function setTransformer() :TransformerAbstract
    {
        return app(UserTransformer::class);
    }
```
2. vendor/bin/phpunit not run < problem : `$this->app->instance(ExceptionHandler::class, new class extends Handler {`>
3. don't run `php artisan route:list` <`oauth2 encryption key issue`>
---
your project have vue.js for need
* npm install

**Comment by juanelojga** [comment]
Hi,

What version of php are you running?
The expressions that you list are only compatible with PHP 7.0 or greater.

**Comment by mostafa6765** [comment]
I am using 5.6.11 . but when install your project by composer requirement 
```php
  "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "joselfonseca/laravel-tactician" : "0.3.*",
        "joselfonseca/laravel-api-tools": "^2.2",
        "laravel/passport": "^2.0",
        "webpatser/laravel-uuid": "^2.0",
        "spatie/laravel-permission": "^1.7"
    },
```

**Comment by juanelojga** [comment]
Maybe you are using an older version, the new one says "php": ">=7.0.0".

**Comment by joselfonseca** [comment]
It is indeed an old version, in the new one we are no longer using Laravel-api-tools. 

Can you clone master and try like that? also if you could tell me what version is getting downloaded when you use composer create project that would help me a lot since is not the first time i hear about this issue.

**Comment by joselfonseca** [comment]
I have installed this several times and i haven't seen this issue, if this appears again please open a new issue.

Thanks!
