### ISSUE TITLE
where is  the usage documentation ?

### ISSUE THREAD

**Issue by othmasoft** [joselfonseca/laravel-api#14]
i installed it 
and can generate access token as password guard 
put it give me 401 Unauthenticated when using it in postman

my post like

GET /api/users HTTP/1.1
Host: pathfinder.local
Accept: application/vnd.api.v1+json
Content-Type: application/json
Authorization: Beare eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImU4MjhlYmY2YTIxYWQzODMzMGJiOWEwN2VkNTgzNWE5ZGEzMjgzNmI0MTdhOTM0ODBkNzYzMGRlMzY0NGZjOTgxZmEyMDU3N2M3MTdjNmQyIn0.eyJhdWQiOiI3IiwianRpIjoiZTgyOGViZjZhMjFhZDM4MzMwYmI5YTA3ZWQ1ODM1YTlkYTMyODM2YjQxN2E5MzQ4MGQ3NjMwZGUzNjQ0ZmM5ODFmYTIwNTc3YzcxN2M2ZDIiLCJpYXQiOjE0OTk4MjQ3MjksIm5iZiI6MTQ5OTgyNDcyOSwiZXhwIjoxNDk5ODYwNzI4LCJzdWIiOiIxIiwic2NvcGVzIjpbIioiXX0.DiHMB0t84W12kJ4TDg_osubovyDNH5UNUR5Lc2EPfy77z75WMRQAM9y_qnQ3GXneaFdj6u4BHemdUD2KOTE_ctT6eztCZ7gRLCLT0xNnwZxzT3Hn-gjf0K5-S0BkwEaMEQWykMEpi2joKu8k1pV5Wr2ahCWfLA9XjSUycFjWbYV9CJvQC6eype0d6QCKwmzfz-fb7j8WcctoxO-d041AJxRvYPFXd1SPtW8TLcy3DrJfGYDqmy-BRg5o7Jway1wbyAnvk4pRRanSwjNCCq14wiO_hdfsPEL9qCY57mzwhyRt3nRJyoX0nAxpKkrz4ogXDH0v1Smmch5gVSP0xmspFnOgtT1wAjJNukC68aEUybAcvpvPyZc0sg0tAUX8L9o1h-w-8gQodYaoyxB9EDMnjBC-cEpk9Kbpy_2DMy0o8OBEKcD1LKOQS1Tsw7403_XEOjjjnEcFDkgEoJeM7ocrS0Qnka8Ui8wibCM_jTDeqLTctD1VC3Gtu7iRZWOmPvY_V-LMwLGgd7T_rBLAugKha3NACgRQXIH2uuqpD_eysqab5aOiJxgG04O4n4q6F9i7XVZD1JnLir_gg6xY5Qs2FrS_CrEZYMUWVIbTumyi0MGUcZz2sqXgvfgEdzYGkQd0G0RmRbM7HTZOnME61G4oEKXf5yDj69YWLPVeukuQN34
Cache-Control: no-cache
Postman-Token: 26df83db-e57b-9853-f8b9-6c9d04f8d5cc

**Comment by joselfonseca** [comment]
you have `Beare` in your HTTP request, it should be `Bearer`.

**Comment by othmasoft** [comment]
Thanks joselfonseca it work fine

**Comment by sbn111** [comment]
I have the same issue. Pls help to solve this.
