### ISSUE TITLE
small typo in roles controller

### ISSUE THREAD

**Issue by kslimani** [joselfonseca/laravel-api#15]
I think there is a small typo [here](https://github.com/joselfonseca/laravel-api/blob/master/app/Http/Controllers/Api/Users/RolesController.php#L105) (doesn't should be `$role` instead of `$user` ?) - the code is working, it is only variable name. (_not sure if it worth a PR 😸_)

**Comment by joselfonseca** [comment]
It is a typo. I will fix it later today or tomorrow, Thanks for noticing that!

**Comment by joselfonseca** [comment]
Fixed here https://github.com/joselfonseca/laravel-api/releases/tag/3.1.0
