### ISSUE TITLE
Feat request : upgrade Laravel passport to version 3.0.0

### ISSUE THREAD

**Issue by kslimani** [joselfonseca/laravel-api#16]
I think it would be nice to upgrade `laravel/passport` to `^3.0` which will also upgrade `league/oauth2-server` to `6.0.0`.

I locally upgraded and run tests and they all passed.

Motivations is it fixes [security issues](https://github.com/thephpleague/oauth2-server).

Here the diff for passport from [2.0.11 to 3.0.0](https://github.com/laravel/passport/compare/v2.0.11...3.0). I don't see major breaking changes, except for the key encrypt part fix. (_but you may want to double check this_).

Here the diff for oauth from [5.1.3 to 6.0.0](https://github.com/thephpleague/oauth2-server/compare/5.1.3...6.0.0). Major changes seems to be related to file permissions for key files. (_you may also want to double check this_).

EDIT: for League oauth server, it seems it require [one line to be changed](https://oauth2.thephpleague.com/v5-security-improvements/).

**Comment by joselfonseca** [comment]
Great catch, I though i did it before. I will update this repo today. Thanks!

**Comment by joselfonseca** [comment]
Fixed here https://github.com/joselfonseca/laravel-api/releases/tag/3.1.0
