### ISSUE TITLE
Question: is 3.1.0 production ready ?

### ISSUE THREAD

**Issue by kslimani** [joselfonseca/laravel-api#18]
@joselfonseca do you think that current release 3.1.0 could be used in production as base api skeleton or do you think it still require some work ? (_my knowledge in api is low and this project is very great !_)

**Comment by joselfonseca** [comment]
Thanks for the question and feedback. It is ready. We use it in different projects already, in fact some on the bug fixes and features came from our propietary work. Keep in mind that the requirements for your project may require other modifications to the initial skeleton, but most cases go ok with this starting point and then anything else you add is usually project specific.

**Comment by kslimani** [comment]
Thank you @joselfonseca for confirmations. 👍
