### ISSUE TITLE
Add PHP 7.0 Constraint in composer.json

### ISSUE THREAD

**Issue by unexpected5** [joselfonseca/laravel-api#2]
When try to Php artisan app:install
unable to figure it  out the problem 

PHP Parse error:  parse error, expecting `';'' or `'{'' in /Library/WebServer/Documents/new-api/app/Services/Users/UsersService.php on line 76

                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  parse error, expecting `';'' or `'{''

**Comment by joselfonseca** [comment]
Hello,

Are you using PHP 5.6 or older? This is the line

https://github.com/joselfonseca/laravel-api/blob/2.0/app/Services/Users/UsersService.php#L76

It requires PHP 7.0 or greater. I should probably add that constraint to the composer.json, I will do.

Thanks!

**Comment by unexpected5** [comment]
Thanks i am upgrading my php to v 7.0 will update the result

**Comment by unexpected5** [comment]
mean while i faced the another error on npm run dev  is any version error here module.js:471
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by joselfonseca** [comment]
Did you installed the NPM dependencies?

**Comment by joselfonseca** [comment]
Constraint added in https://github.com/joselfonseca/laravel-api/commit/a259b13ee83819d93bcdcf8e236d84f33664d596
