### ISSUE TITLE
Pagination link is missing some parameters

### ISSUE THREAD

**Issue by kslimani** [joselfonseca/laravel-api#20]
In the "index" methods of controllers, i see that the `limit` query parameter [is handled](https://github.com/joselfonseca/laravel-api/blob/master/app/Http/Controllers/Api/Users/UsersController.php#L49) to modify  the default pagination. But i see that the `appends()` paginator method is not used to pass at least the `limit` parameter so it is missing in the generated link in response pagination metadata.

Maybe add something like `->appends($request->only('limit'))` (_and let developer decide if it allow more ? dunno if `$request->all()` may be a security issue here_).

@joselfonseca what is your opinion on this ?

**Comment by joselfonseca** [comment]
This seems fine, i will look into it and see what can be done. or if you have an idea PRs are welcome! 

Thanks!

**Comment by joselfonseca** [comment]
How about this

https://github.com/joselfonseca/laravel-api/commit/9d821ede176ebb0bdc2e7c805033179a4256f9fc

Added tests to it.

**Comment by kslimani** [comment]
👍 thx !

LGTM. I noted also that paginator `appends()` method can accept an array as argument; ie: single line
```php
$paginator->appends($request->only('limit'));
```

**Comment by joselfonseca** [comment]
good catch. I may change it then.
