### ISSUE TITLE
Bug with HasRolesUuid and HasPermissionsUuid

### ISSUE THREAD

**Issue by kslimani** [joselfonseca/laravel-api#35]
There is an issue i missed when i proposed to upgrade laravel-permission to 2.4 : role and permissions are retrieved from database by name but using also guard name. (_the logic is in the Spatie Role and Permission findByName methods_).

Result is, for example, when using `$user->hasRole('role-name')`, it request from database by name or uuid, but not guard name : this is an issue when using multiple guards.

I don't know yet how to fix this. (_we could add guard name in the where condition in traits, but i dunno if it is the best way as it may be problematic to maintain_).

Maybe simply drop support for checking if a user has role or permission by uuid could be a solution for fix this issue ? In fact, is checking a role by uuid instead of name usefull ?

**Comment by kslimani** [comment]
@joselfonseca i think you can close this issue : it's been a long time and noone reported any issue _(using multiple guard is not a common use case, and if required developper can modify the role uuid trait to his needs)_

**Comment by joselfonseca** [comment]
Nice, Thanks! @kslimani
