### ISSUE TITLE
Drop Dingo API

### ISSUE THREAD

**Issue by joselfonseca** [joselfonseca/laravel-api#36]
Hey @kslimani 

What do you think about dropping Dingo as it is not really being maintained? Can you tell me what specific things from Dingo you are tied to or want to still see in the starter kit. Also keep in mind that we now have Resources (https://laravel.com/docs/5.5/eloquent-resources) in Laravel so we could drop Fractal as well. 

Let me know what you think.

**Comment by kslimani** [comment]
Hello @joselfonseca,

Unless Laravel 5.5 support is added to Dingo, i see no immediate alternative than dropping it. (_afaik, if not dropped, upgrading starter kit to Laravel 5.5 may be tricky_).

Lost features are, i think, route versioning, content negotiation and maybe api blueprint documentation (_but find an api documentation alternative should not be that complex_).

_Personally_, i am not tied to any of these features (_but some people may care, especially on route versioning_).

Fractal seems to be Dingo peer dependency. Dingo adds some feature like automatic model include relationship. It seems it can be reproduced with _Resources_ using the _Conditional Relationships_ feature. (_it did not yet test myself, only read the docs_).

**Comment by joselfonseca** [comment]
Yes, I think route versioning is what i am more tied to in Dingo, that part is just great, the problem is that Dingo has not have much activity lately and i am afraid the package may loose support soon if no one else takes it. That is my main concern.

Do you know or anyone else knows any alternatives to the Route versioning by header feature dingo provides?

Fractal is indeed required by Dingo, i was thinking more about the transformers, like changing them to use resources.

**Comment by joselfonseca** [comment]
Turns out Dingo is compatible with Laravel 5.5 and a new project was open to continue the support of it.
