### ISSUE TITLE
[Question] How do you generate blueprint api documentation?

### ISSUE THREAD

**Issue by sctteea** [joselfonseca/laravel-api#39]
I tried using:

> php artisan api:docs --name Docs

but it only exports 3 lines:

> FORMAT: 1A
> 
> \# Docs

How are the .apib view files being generated?

**Comment by kslimani** [comment]
Take a look at [this project](https://github.com/danielgtaylor/aglio).

Just do a `npm install -D aglio` (or install globally), then just add an npm tasks in your package.json file

```javascript
{
    "scripts": {
        "apidoc-dist": "aglio -i path/to/index.apib -o path/to/file.html",
        "apidoc-watch": "aglio -s -h 0.0.0.0 -p 3000 -i path/to/index.apib"
    },
 }
```

**Comment by joselfonseca** [comment]
@sctteea Thanks for the question, the API blueprint file is written manually, we are not using annotations to generate it. We found out that that does not generate the docs how we want them. We do use aglio to generate the HTML out. You can add the annotations to the controllers and generate the apib file that way if you want.
