### ISSUE TITLE
Table should not be migrate

### ISSUE THREAD

**Issue by Raushn** [joselfonseca/laravel-api#40]
In Connection.php line 664:

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No such host is known.  (SQL: insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revok
  ed`, `updated_at`, `created_at`) values (, Laravel API Personal Access Client, nBN4Cssau7Xbbe6bDJVbqpN50LrooVB9OdHWB8dn, http://localhost, 1, 0, 0, 2018-08-24 11:15:44, 2018-08-24 11:15:44))

In Connector.php line 68:

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No such host is known.

In Connector.php line 68:

  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: No such host is known.

**Comment by kslimani** [comment]
It seems to be a database configuration issue. What is the database "host" configured ?

**Comment by Raushn** [comment]
Where is the Admin Panel?

**Comment by kslimani** [comment]
laravel-api is an http api project based on Laravel framework. To configure a database, please refer to [the Laravel official documentation](https://laravel.com/docs/5.6/database).
