### ISSUE TITLE
[FR] - Drop dingo?

### ISSUE THREAD

**Issue by joselfonseca** [joselfonseca/laravel-api#41]
@kslimani What do you think about dropping dingo for the following reasons:

- Reduce 3rd party dependencies
- Encourage API Evolution instead of API Versioning (https://blog.apisyouwonthate.com/api-evolution-for-rest-http-apis-b4296519e564)
- Change Fractal in favor of native Resources (https://laravel.com/docs/5.6/eloquent-resources)

Also for the Spec change API Blueprint in favor of OpenAPI 3.0 spec.

**Comment by kslimani** [comment]
@joselfonseca "API evolution" is the methodology i already use for my applications.

By dropping Dingo, you lose the "mime based" ressource versioning feature, but you can still use "URL based" ressource versioning. _(so I am not against dropping Dingo dependency)_.

About replacing Fractal by Eloquent Resources : i have not yet myself tested this feature. It seems powerfull but i don't know how it handle the pagination for collection, especially the links in meta.

Do you know if it is automatically handled by Laravel or do you have to generate the url links yourself  ?
_(if not, it may be required to create some helpers to reproduce the Dingo collection metadata)_

About the OpenAPI spec i don't know, i think it may depends on the available tools to generate api documentation. (Aglio is pretty cool for API blueprint format).

**Comment by kslimani** [comment]
I have read the pagination part for API resources, i was just wondering how the urls in "links" and "meta" are generated in the provided example :

```php
// Copy paste from https://laravel.com/docs/5.6/eloquent-resources#pagination
use App\User;
use App\Http\Resources\UserCollection;

Route::get('/users', function () {
    return new UserCollection(User::paginate());
});
```

**Comment by joselfonseca** [comment]
Yea, I was looking into that and got this:

```php
[
  "data" => array:0 []
  "links" => array:4 [
    "first" => "http://localhost/api/users?page=1"
    "last" => "http://localhost/api/users?page=2"
    "prev" => null
    "next" => "http://localhost/api/users?page=2"
  ]
  "meta" => array:7 [
    "current_page" => 1
    "from" => 1
    "last_page" => 2
    "path" => "http://localhost/api/users"
    "per_page" => 20
    "to" => 20
    "total" => 31
  ]
```
Using 

```php
    /**
     * Returns the Users resource with the roles relation.
     *
     * @param Request $request
     * @return mixed
     */
    public function index(Request $request)
    {
        $paginator = $this->model->with('roles.permissions')->paginate($request->get('limit', config('app.pagination_limit')));
        if ($request->has('limit')) {
            $paginator->appends('limit', $request->get('limit'));
        }

        return UserResource::collection($paginator);
    }
```

data is empty because I removed it, but the user data is there. I am only worried about like the includes, have not seen how that works.

**Comment by kslimani** [comment]
What happen if instead of `/users` you rename to something else ?

```php
Route::get('/foobar', function () {
    return new UserCollection(User::paginate());
});
```
Does it properly generate links like `http://localhost/api/foobar?page=1` ?

**Comment by joselfonseca** [comment]
It actually does XD 

```php
  "links" => array:4 [
    "first" => "http://localhost/api/foo?page=1"
    "last" => "http://localhost/api/foo?page=2"
    "prev" => null
    "next" => "http://localhost/api/foo?page=2"
  ]
  "meta" => array:7 [
    "current_page" => 1
    "from" => 1
    "last_page" => 2
    "path" => "http://localhost/api/foo"
    "per_page" => 20
    "to" => 20
    "total" => 31
  ]
```

```php 
Route::group(['prefix' => 'foo'], function () {
        Route::get('/', 'Users\UsersController@index');
```
```php
/**
     * Returns the Users resource with the roles relation.
     *
     * @param Request $request
     * @return mixed
     */
    public function index(Request $request)
    {
        $paginator = $this->model->with('roles.permissions')->paginate($request->get('limit', config('app.pagination_limit')));
        if ($request->has('limit')) {
            $paginator->appends('limit', $request->get('limit'));
        }

        return UserResource::collection($paginator);
    }
```

**Comment by kslimani** [comment]
That's pretty cool !

**Comment by joselfonseca** [comment]
Lets leave this for later XD.
