### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by devman113** [joselfonseca/laravel-api#45]
Thanks for creating a great stuff.
After following all steps, I could run 127.0.0.1:8000 and API explorer screen.
I also created the passport client called 'admin'.
What should I do next?
I get Unauthorized bugs when I run `http://127.0.0.1:8000/api/users`

**Comment by joselfonseca** [comment]
Thank, you should use passport's endpoints to create a new access token.

https://laravel.com/docs/5.7/passport#issuing-access-tokens

The API is secured with Laravel passport so you should be able to generate tokens and use them according to Passport's documentation

https://laravel.com/docs/5.7/passport
