### ISSUE TITLE
Openapi3 docs update

### ISSUE THREAD

**Issue by codeace** [joselfonseca/laravel-api#57]
What package can I use to update the existing api documentation after making changes?
Thank

**Comment by kslimani** [comment]
I think it was originally rendered with [Aglio](https://github.com/danielgtaylor/aglio).

It may also worth to take a look at [Dingo API blueprint documentation](https://github.com/dingo/api/wiki/API-Blueprint-Documentation)  _(they made some progress in latest dingo api release)_.

**Comment by codeace** [comment]
> I think it was originally rendered with [Aglio](https://github.com/danielgtaylor/aglio).
> 
> It may also worth to take a look at [Dingo API blueprint documentation](https://github.com/dingo/api/wiki/API-Blueprint-Documentation) _(they made some progress in latest dingo api release)_.

Awesome, thanks
