### ISSUE TITLE
How can I login using api

### ISSUE THREAD

**Issue by AleksandrAsanov** [joselfonseca/laravel-api#59]
I am going to get an authentication token on postman using username and password
But I can't.
![image](https://user-images.githubusercontent.com/45660446/71745447-1d0b9000-2ea5-11ea-8be4-db4bcd61dfe6.png)
![image](https://user-images.githubusercontent.com/45660446/71745474-298fe880-2ea5-11ea-9bc1-4e7c2516af04.png)
Please help me

**Comment by kslimani** [comment]
@AleksandrAsanov check your token request URL _(i don't think it is ending with 's')_

Double check Laravel Passport [password-token documentation](https://laravel.com/docs/6.x/passport#password-grant-tokens).

**Comment by AleksandrAsanov** [comment]
Thank you so much!
