### ISSUE TITLE
FatalErrorException in RegisterController.php line 65: Class 'App\User' not found

### ISSUE THREAD

**Issue by grajkamal9** [joselfonseca/laravel-api#6]

**Comment by joselfonseca** [comment]
Thanks,
In this line https://github.com/joselfonseca/laravel-api/blob/2.0/app/Http/Controllers/Auth/RegisterController.php#L5 it should reference `App\Entities\User` instead, I will add a fix to this in 3.0 which is being worked now.

**Comment by grajkamal9** [comment]
Thank you Joselfonseca.
