### ISSUE TITLE
Is it possible to register without login

### ISSUE THREAD

**Issue by dream811** [joselfonseca/laravel-api#60]
I am going to use this as a back-end of a spa (front-end will be react).
so I need to login, registration forget password and reset password script.
any good idea?

**Comment by joselfonseca** [comment]
Yes it will work as a backend for SPA. For login you have the Passport routes to get an access token, what we don't have here is registration and forgot password routes. Could be a good addition although it depends many times on the app business rules. If you want to work on those endpoints and ser a PR it will be welcome.

**Comment by dream811** [comment]
Thank you and your awesome project.
