### ISSUE TITLE
Upgrade to Laravel 7

### ISSUE THREAD

**Issue by joselfonseca** [joselfonseca/laravel-api#62]

**Comment by AbdullaevTimur** [comment]
The api is currently compatible with laravel 7?

**Comment by joselfonseca** [comment]
The started kit is currently using Laravel 6, I have not have the time to upgrade it to 7 although is really just update packages. PRs are welcome.

**Comment by joselfonseca** [comment]
Added in https://github.com/joselfonseca/laravel-api/releases/tag/9.0.0

**Comment by AbdullaevTimur** [comment]
Great!) Thanks!
