### ISSUE TITLE
Update Scaffold to Laravel 8

### ISSUE THREAD

**Issue by joselfonseca** [joselfonseca/laravel-api#67]

**Comment by AbdullaevTimur** [comment]
Waiting for)

**Comment by joselfonseca** [comment]
Working on this here https://github.com/joselfonseca/laravel-api/commit/6ba28ffe58ee616ccfafea85272eb96482eec1dc Need to add more coverage in the tests

**Comment by joselfonseca** [comment]
Fixed it here https://github.com/joselfonseca/laravel-api/releases/tag/10.0.0
