### ISSUE TITLE
laravel 7 User does not have the right permissions.

### ISSUE THREAD

**Issue by k2gsalem** [joselfonseca/laravel-api#69]
User does not have the right permissions. error showing
    "message": "User does not have the right permissions.",
    "status_code": 403,
    "debug": {
        "line": 37,

**Comment by joselfonseca** [comment]
Hi there, I am not sure I understand the issue, that means the user you are using to query the API does not have the permission for the endpoint you are calling.

**Comment by k2gsalem** [comment]
Some time Web guard not defined error also coming

**Comment by joselfonseca** [comment]
Please provide a PR with a failing test to validate if there is an issue. I think we are missing a lot of information about the use case.

**Comment by joselfonseca** [comment]
Not considered an issue without a failing test or more information. Closing for now.
