### ISSUE TITLE
ParseError: syntax error when running through localhost xampp

### ISSUE THREAD

**Issue by sbn111** [joselfonseca/laravel-api#88]
Showing the following error while trying to get users list,

ParseError: syntax error, unexpected 'Parser' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in file E:\xampp\htdocs\new-api\vendor\lcobucci\jwt\src\Configuration.php on line 22

#0 E:\xampp\htdocs\new-api\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('E:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Lcobucci\\JWT\\Co...')
#2 E:\xampp\htdocs\new-api\vendor\league\oauth2-server\src\AuthorizationValidators\BearerTokenValidator.php(74): spl_autoload_call('Lcobucci\\JWT\\Co...')
#3 E:\xampp\htdocs\new-api\vendor\league\oauth2-server\src\AuthorizationValidators\BearerTokenValidator.php(66): League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator->initJwtConfiguration()
#4 E:\xampp\htdocs\new-api\vendor\league\oauth2-server\src\ResourceServer.php(67): League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator->setPublicKey(Object(League\OAuth2\Server\CryptKey))
#5 E:\xampp\htdocs\new-api\vendor\league\oauth2-server\src\ResourceServer.php(84): League\OAuth2\Server\ResourceServer->getAuthorizationValidator()
#6 E:\xampp\htdocs\new-api\vendor\laravel\passport\src\Guards\TokenGuard.php(204): League\OAuth2\Server\ResourceServer->validateAuthenticatedRequest(Object(Nyholm\Psr7\ServerRequest))
#7 E:\xampp\htdocs\new-api\vendor\laravel\passport\src\Guards\TokenGuard.php(147): Laravel\Passport\Guards\TokenGuard->getPsrRequestViaBearerToken(Object(Illuminate\Http\Request))
#8 E:\xampp\htdocs\new-api\vendor\laravel\passport\src\Guards\TokenGuard.php(110): Laravel\Passport\Guards\TokenGuard->authenticateViaBearerToken(Object(Illuminate\Http\Request))
#9 E:\xampp\htdocs\new-api\vendor\laravel\passport\src\PassportServiceProvider.php(308): Laravel\Passport\Guards\TokenGuard->user(Object(Illuminate\Http\Request))
#10 [internal function]: Laravel\Passport\PassportServiceProvider->Laravel\Passport\{closure}(Object(Illuminate\Http\Request), NULL)
#11 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Auth\RequestGuard.php(58): call_user_func(Object(Closure), Object(Illuminate\Http\Request), NULL)
#12 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Auth\GuardHelpers.php(60): Illuminate\Auth\RequestGuard->user()
#13 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(63): Illuminate\Auth\RequestGuard->check()
#14 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(42): Illuminate\Auth\Middleware\Authenticate->authenticate(Object(Illuminate\Http\Request), Array)
#15 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#16 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(694): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(669): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#19 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#20 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(166): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#23 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 E:\xampp\htdocs\new-api\vendor\fruitcake\laravel-cors\src\HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 E:\xampp\htdocs\new-api\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(141): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 E:\xampp\htdocs\new-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#38 E:\xampp\htdocs\new-api\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#39 {main}

**Comment by joselfonseca** [comment]
this seems a PHP version issue, what PHP version are you using?

**Comment by sbn111** [comment]
> 
> 
> this seems a PHP version issue, what PHP version are you using?

Using php version 7.2.32

It is working if I run using php artisan serve, But I am receiving invalid_grant error response. Could you pls look this?

**Request:-**
URL - http://127.0.0.1:8000/oauth/token
{
  "grant_type": "password",
  "client_id": "8",
  "client_secret": "87jd6NA5DEA9r868XZEXL1jPN9U4hGmv0ZoGkfo3",
  "username": "jose@example.com",
  "password": "Password123**"
}

**Response:-**
{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
    "hint": "",
    "message": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}


I have tried by changing grant type to client_credentials,  but it not worked properly

Kindly help for the project setup. Thanks in advance
