### ISSUE TITLE
Is this any option with pagination and filter while taking list user

### ISSUE THREAD

**Issue by sbn111** [joselfonseca/laravel-api#91]
Is this any option with pagination and filter while taking list user. It will help if your project has this funtion. Thanks

**Comment by joselfonseca** [comment]
Not at the moment, we haven't implemented that, this is a starter kit so you can start not from 0 but from something. from this point on you can add any features you want in your project.

**Comment by sbn111** [comment]
Okay thank you


Saravanabavan Subbarayalu,

Developer, Newlineinfo

Skype: .cid.f556a42cf7331e84
Contact No: +91 8825975530

www.newlineinfo.in

Confidentiality Note: This email may contain confidential and/ or private
information and is intended only for the individual(s) or entities to whom
it is addressed. If you received this email in error, please delete and
notify the sender.
