### ISSUE TITLE
internal api/asset with file upload not working

### ISSUE THREAD

**Issue by k2gsalem** [joselfonseca/laravel-api#97]
Error: Call to a member function getRealPath() on array in file C:\xampp\htdocs\textile8\app\Http\Controllers\Api\Assets\UploadFileController.php on line 57

**Comment by k2gsalem** [comment]
$req=Request::create('api/assets','POST',['file'=>$file]);               
  $assets= Route::dispatch($req);

**Comment by k2gsalem** [comment]
Dingo Api Internal call Working properly in laravel 7 .
How to call Internal api with file

**Comment by joselfonseca** [comment]
This starter kit does not use Dingo API.
